### ISSUE TITLE
Uncaught AttributeError: 'module' object has no attribute 'GRA_Max'


### ISSUE THREAD

**Issue by 1mush** [lutraconsulting/qgis-report-plugin#39]
Couldn't load plugin 'processing'
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 308, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\__init__.py", line 28, in <module>
    from processing.tools.dataobjects import *          # NOQA
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\tools\dataobjects.py", line 37, in <module>
    from processing.algs.gdal.GdalUtils import GdalUtils
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing\algs\gdal\GdalUtils.py", line 32, in <module>
    from osgeo import gdal
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\osgeo\gdal.py", line 116, in <module>
    from gdalconst import *
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\osgeo\gdalconst.py", line 148, in <module>
    GRA_Max = _gdalconst.GRA_Max
AttributeError: 'module' object has no attribute 'GRA_Max'

```
report 0.2.1, QGIS 2.18.14 on Windows 8

**Comment by PeterPetrik** [comment]
should be raised in processing repo
