### ISSUE TITLE
Uncaught AttributeError: 'module' object has no attribute 'GRA_Max'


### ISSUE THREAD

**Issue by 1mush** [lutraconsulting/qgis-report-plugin#40]
Couldn't load plugin GdalTools due to an error when calling its classFactory() method
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\GdalTools\__init__.py", line 24, in classFactory
    from .GdalTools import GdalTools
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\GdalTools\GdalTools.py", line 33, in <module>
    from osgeo import gdal  # NOQA
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\osgeo\gdal.py", line 116, in <module>
    from gdalconst import *
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\osgeo\gdalconst.py", line 148, in <module>
    GRA_Max = _gdalconst.GRA_Max
AttributeError: 'module' object has no attribute 'GRA_Max'

```
report 0.2.1, QGIS 2.18.14 on Windows 8

**Comment by PeterPetrik** [comment]
should be raised in GdalTools repository
